
name: readwiser
services:

  api:
    build: .
    container_name: readwiser-api
    environment:
      "DataStore:MongoDb:ConnectionString": "mongodb://mongo:27017"
      "DataStore:MongoDb:Database": "readwiser"
      "ApiKey": "zf496N7o5Sq8sCagvxS99ReRp9QCj8f2MteGwhNfk9NMhCk9"

    ports:
      - 5113:80
      - 7113:443

  mongo:
    container_name: mongo
    ports:
      - 27017:27017
    volumes:
      - ./mongodb_data:/data/db
    image: mongo