
name: readwiser
services:

  web:
    # build: bramvandenbussche.readwiser.web/.
    image: readwiser-web
    container_name: web
    depends_on:
      - mongo

    environment:
      "DataStore:MongoDb:ConnectionString": "mongodb://mongo:27017"
      "DataStore:MongoDb:Database": "readwiser"
      "ApiKey": "zf496N7o5Sq8sCagvxS99ReRp9QCj8f2MteGwhNfk9NMhCk9"

    ports:
      - 5114:8080

  api:
    # build: bramvandenbussche.readwiser.api/.
    image: readwiser-api
    container_name: api
    depends_on:
      - mongo

    environment:
      "DataStore:MongoDb:ConnectionString": "mongodb://mongo:27017"
      "DataStore:MongoDb:Database": "readwiser"
      "ApiKey": "zf496N7o5Sq8sCagvxS99ReRp9QCj8f2MteGwhNfk9NMhCk9"

    ports:
      - 5113:8080


  mongo:
    container_name: mongo
    ports:
      - 27017:27017
    volumes:
      - ./mongodb_data:/data/db
    image: mongo