
@api-key = ABC123
@title = Test
@author = Bram

######
### Get all notes and highlights

GET {{api-base-url}}/api/highlight
Authorization: Token {{api-key}}


######
### Get all notes and highlights for one book

GET {{api-base-url}}/api/highlight/book?title={{title}}&author={{author}}
Authorization: Token {{api-key}}



######
### Create new highlight

POST {{api-base-url}}/api/highlight
content-type: application/json
Authorization: Token {{api-key}}

{
  "highlights": [
    {
      "title": "{{title}}",
      "text": "Lorem Ipsum",
      "author": "{{author}}",
      "chapter": "Chapter 1",
      "note": "hello world!"
    }
  ]
}