
@title = Golden Son
@author = Pierce Brown
@api-key = ABC123

######
### Get all notes and highlights

GET {{api-base-url}}/api/highlight
Authorization: Token {{api-key}}


######
### Get all notes and highlights for one book

GET {{api-base-url}}/api/highlight/book?title={{title}}&author={{author}}



######
### Create new highlight

POST {{api-base-url}}/api/highlight
content-type: application/json

{
  "highlights": [
    {
      "title": "Red Rising",
      "text": "The suit is some kind of nanoplastic and is hot as its name suggests.",
      "author": "Pierce Brown",
      "chapter": "1: Helldiver"
    }
  ]
}